Add inviscid unsteady test
smdogroup/funtofem pull request #221
Opened 2023-09-01 21:43 UTC by bburke38

Adds a test for unsteady FUN3D+TACS fully coupled discipline derivatives. Right now, this only tests inviscid along the aeroelastic path. Currently, the structural functions are failing while lift and drag seem to be passing. However, changing `flow_dt` in the Python run script seems to have no impact on the test results. Changing the time step set to TACS also has limited effect.

2023-09-01 22:00 UTC, sean-engelstad commented
Can you remove the .DS_store files?

2023-09-05 02:19 UTC, sean-engelstad requested changes
Please remote the DS_Store files first

2023-09-05 02:19 UTC, sean-engelstad commented on tests/fun3d_tests/fully_coupled_disc_deriv_unsteady/euler-AE/meshes/inviscid/Adjoint/.DS_Store
@Can you delete this file and the other **/.DS_Store files?

2023-09-05 02:44 UTC, bburke38 commented on tests/fun3d_tests/fully_coupled_disc_deriv_unsteady/euler-AE/meshes/inviscid/Adjoint/.DS_Store
Okay, just make sure to add the necessary folders back. The .DS_Store files seem to help keep the directory structure.

2023-09-05 02:44 UTC, merged