Unsteady debug statements
smdogroup/funtofem pull request #229
Opened 2023-09-19 18:01 UTC by bburke38

- Create debug flags for fun3d_interface and nlbgs driver
- Print out some adjoint variables, struct_loads, aero_loads, etc.

2023-09-20 01:55 UTC, sean-engelstad commented
Can you make it so we only print out the real and imaginary norms, not the vector? I don't think the vector is helpful. Maybe something like this. And maybe we can save the definition of real and imaginary norms in one of the utils python modules or something so you can use it in different files
```
def real_norm(vec):
    return np.max(np.abs(np.real(vec))) # or do a np.linalg.norm either one
def imag_norm(vec):
    return np.max(np.abs(np.imag(vec)))
if struct_loads is not None:
    print(f"struct loads real step{step} = {real_norm(struct_loads)}")
    print(f"struct loads imag step{step} = {imag_norm(struct_loads)}", flush=True)
```

2023-09-20 01:55 UTC, sean-engelstad commented
Also why is the test failing now?

2023-09-20 15:45 UTC, bburke38 commented
I missed some checks for none types, I'll add those this afternoon.

2023-09-21 17:21 UTC, bburke38 commented
I added a None check inside the new utilities functions. That way, if the array is None it automatically will print out NoneType instead of throwing an error from linalg.norm.

2023-09-21 17:29 UTC, sean-engelstad requested changes
I think we should add some root proc checks in case we are debugging in the large proc case. As far as I can tell, I think printing out on the root proc only is good (only in rare cases would we need to print out the norms for each individual proc).

2023-09-21 17:29 UTC, sean-engelstad commented on funtofem/driver/funtofem_nlbgs_driver.py
> +                if self._debug:
You need a self.comm.rank == 0 check here so for large proc cases you don't print this out 48 times, etc. If you do want it to print out for every processor then we should have a different debug mode like `debug = "all"`, `debug = "root"` and `debug=None` or something.
```suggestion
                if self._debug and self.comm.rank == 0:
```

2023-09-21 17:29 UTC, sean-engelstad commented on funtofem/driver/funtofem_nlbgs_driver.py
> +                if self._debug:
See above, comm check needed here, I'm not going to repeat this comment for the other ones.

2023-09-21 19:40 UTC, sean-engelstad approved these changes
Comm checks were added. Approved

2023-09-26 20:22 UTC, merged