Fun3d 14.0.2 Stable Release
smdogroup/funtofem pull request #288
Opened 2024-03-07 04:05 UTC by sean-engelstad

* Fun3dThermalInterface used to debug the aerothermal path which was causing error in the FUN3D 14.0.2 release.
* Bug for aerothermal path was fixed and the finite difference derivatives for all subcases of AE, AT, ATE coupling pass to 1e-8 or better accuracy with a central difference approximation (FD vs adjoint).
* A couple of changes to the imports for mphys in the case that openmdao is not available (to prevent the whole package from not importing).

2024-03-07 19:10 UTC, sean-engelstad commented on tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/test_fun3d_tacs.py
done

2024-03-07 19:11 UTC, sean-engelstad commented on funtofem/model/body.py
done

2024-03-07 19:11 UTC, sean-engelstad commented on tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/test_fun3d_tacs.py
done

2024-03-07 19:51 UTC, bburke38 requested changes

2024-03-07 19:51 UTC, bburke38 commented on tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/test_fun3d_tacs.py
Can you change this one back to testing FUN3D v13?

2024-03-07 21:16 UTC, sean-engelstad commented on tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/test_fun3d_tacs.py
done now added fun3d project name back in

2024-03-08 01:49 UTC, bburke38 approved these changes

2024-03-08 01:50 UTC, merged